### ISSUE TITLE
Excel sheet with materials is empty

### ISSUE THREAD

**Issue by nuin** [travswim/RPIWeatherStation#3]
Hi

I tried getting the Excel sheet with building materials and it seems empty. I just tried to download on GitHub, didn't clone the repo.

Is it possible to get an ASCII version of the file?

**Comment by travswim** [comment]
Hi @nuin , I was able to download it directly from github and open it and the file was not empty. To make this less difficult for you and others, I will just make a shareable google sheet. Look for a link to it in the `Readme` in the next few hours.

**Comment by nuin** [comment]
Thanks, appreciated.
